version: '3.8'

services:

  service-discovery:
    build:
      context: .
      dockerfile: service-discovery/Dockerfile
    image: service-discovery
    container_name: service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    ports:
      - "8443:8443"
    networks:
      - backend

  proxy-client:
    build:
      context: .
      dockerfile: proxy-client/Dockerfile
    image: proxy-client
    container_name: proxy-client
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    ports:
      - "8888:8888"
    networks:
      - backend

  identity-service:
    build:
      context: .
      dockerfile: identity-service/Dockerfile
    image: identity-service
    container_name: identity-service
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - IDENTITY_DB_HOST=${IDENTITY_DB_HOST}
      - IDENTITY_DB_PORT=${IDENTITY_DB_PORT}
      - IDENTITY_DB_NAME=${IDENTITY_DB_NAME}
      - IDENTITY_DB_USERNAME=${IDENTITY_DB_USERNAME}
      - IDENTITY_DB_PASSWORD=${IDENTITY_DB_PASSWORD}
      - audit.enabled=true
    ports:
      - "8258:8258"
    networks:
      - backend
      - db-net

  property-service:
    build:
      context: .
      dockerfile: property-service/Dockerfile
    image: property-service
    container_name: property-service
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - PROPERTY_DB_HOST=${PROPERTY_DB_HOST}
      - PROPERTY_DB_PORT=${PROPERTY_DB_PORT}
      - PROPERTY_DB_NAME=${PROPERTY_DB_NAME}
      - PROPERTY_DB_USERNAME=${PROPERTY_DB_USERNAME}
      - PROPERTY_DB_PASSWORD=${PROPERTY_DB_PASSWORD}
      - audit.enabled=true
    ports:
      - "8109:8109"
    networks:
      - backend
      - db-net

  system-service:
    build:
      context: .
      dockerfile: system-service/Dockerfile
    image: system-service
    container_name: system-service
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - LOG_DB_HOST=${LOG_DB_HOST}
      - LOG_DB_PORT=${LOG_DB_PORT}
      - LOG_DB_NAME=${LOG_DB_NAME}
      - LOG_DB_USERNAME=${LOG_DB_USERNAME}
      - LOG_DB_PASSWORD=${LOG_DB_PASSWORD}
      - audit.enabled=true
    ports:
      - "8111:8111"
    networks:
      - backend
      - db-net

networks:
  backend:
  db-net:
    external: true
