server:
  port: 8761

spring:
  application:
    name: SERVICE-DISCOVERY

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

resilience4j:
  circuitbreaker:
    instances:
      cloudConfig:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
